dbt_pipeline:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: jhahdzl-bf56635
      user: PROJECT24DBT
      password: L.zak@007
      role: dbt_role
      database: dbt_db
      warehouse: dbt_wh
      schema: dbt_schema
      threads: 10
      client_session_keep_alive: False