dbt_pipeline:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "account_ID"
      user: "your user name"
      password: "your password"
      role: "role"
      database: "name of your database"
      warehouse: "name of your datawarehouse
      schema: "name of your schema"
      threads: 10
      client_session_keep_alive: False
